import{QUESTIONS,RULES}from"./questions.js";import{NEW_MATERIAL_QUESTIONS}from"./materials-2024.js";import{REGULATION_QUESTIONS}from"./materials-regulasi.js";
const L=["A","B","C","D","E"],$=s=>document.querySelector(s),BANK=dedupe([...QUESTIONS,...NEW_MATERIAL_QUESTIONS,...REGULATION_QUESTIONS]);
const state={questions:[],answers:[],flags:[],current:0,participant:"Peserta Tryout",remaining:0,timerId:null,startedAt:null,result:null},lms={questions:[],current:0,locked:false};
function dedupe(a){const s=new Set;return a.filter(q=>{const k=q.question.trim().toLowerCase();if(s.has(k))return false;s.add(k);return true})}
function byCat(c){return BANK.filter(q=>q.category===c)}
function sh(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function qs(q){const t=`${q.module} ${q.question} ${q.explanation||""}`.toLowerCase();let s=0;if(q.category==="SULIT")s+=20;if(q.question.length>160)s+=18;if(q.question.length>100)s+=10;if((q.explanation||"").length>120)s+=12;if(/kasus|jika|dalam hal|apabila|bagaimana|mengapa|analisis|konsekuensi|paling tepat|kecuali|yang benar|pernyataan|akibat hukum|menurut|berdasarkan/i.test(q.question))s+=28;if(/pasal|pp no|permen|perkaban|uupa|apht|skmht|pmpj|buku daftar|protokol|warkah|honorarium|sanksi|schorsing|onzetting|hak tanggungan|pemeliharaan data/i.test(t))s+=18;if(/^(ppat adalah|uupa adalah|pmpj adalah|sertipikat tanah adalah|ippat adalah)/i.test(q.question.trim()))s-=35;if(/dasar/i.test(q.module)&&q.category!=="SANGAT_MUDAH")s-=15;return s}
function wopt(q){const ok=q.options[q.answerIndex],o=sh(q.options);return{...q,options:o,answerIndex:o.indexOf(ok)}}
function buildPacket(){const p=[];Object.entries(RULES).forEach(([c,r])=>{const ranked=sh(byCat(c)).sort((a,b)=>qs(b)+Math.random()*4-qs(a)-Math.random()*4);p.push(...ranked.slice(0,r.take))});return sh(p).map((q,i)=>({...wopt(q),id:i+1}))}
function renderBankStats(){$("#hardBank").textContent=byCat("SULIT").length;$("#mediumBank").textContent=byCat("MUDAH").length;$("#basicBank").textContent=byCat("SANGAT_MUDAH").length}
function setTab(m){$("#tabTryout").classList.toggle("active",m==="tryout");$("#tabLms").classList.toggle("active",m==="lms");$("#tryoutView").classList.toggle("hidden",m!=="tryout");$("#lmsView").classList.toggle("hidden",m!=="lms")}
function startExam(){state.questions=buildPacket();state.answers=Array(state.questions.length).fill(null);state.flags=Array(state.questions.length).fill(false);state.current=0;state.participant=$("#candidateName").value.trim()||"Peserta Tryout";state.remaining=Math.min(Math.max(Number($("#durationInput").value)||120,10),240)*60;state.startedAt=new Date;state.result=null;$("#participantLabel").textContent=state.participant;$("#maxScore").textContent=maxScore(state.questions).toFixed(6);$("#startPanel").classList.add("hidden");$("#examPanel").classList.remove("hidden");$("#resultPanel").classList.add("hidden");$("#reviewPanel").classList.add("hidden");buildNumberGrid();renderQuestion();renderProgress();startTimer()}
function startTimer(){clearInterval(state.timerId);renderTimer();state.timerId=setInterval(()=>{state.remaining--;renderTimer();if(state.remaining<=0)finishExam()},1000)}
function renderTimer(){const x=Math.max(state.remaining,0),h=Math.floor(x/3600),m=Math.floor(x%3600/60),s=x%60;$("#timer").textContent=[h,m,s].map(v=>String(v).padStart(2,"0")).join(":")}
function buildNumberGrid(){const g=$("#numberGrid");g.innerHTML="";state.questions.forEach((_,i)=>{const b=document.createElement("button");b.className="num";b.type="button";b.textContent=i+1;b.onclick=()=>{state.current=i;renderQuestion()};g.append(b)})}
function renderQuestion(){const q=state.questions[state.current],r=RULES[q.category];$("#questionNumber").textContent=`Soal ${state.current+1} dari ${state.questions.length}`;$("#questionCategory").textContent=r.label;$("#questionModule").textContent=q.module;$("#questionText").textContent=q.question;const list=$("#optionList");list.innerHTML="";q.options.forEach((o,i)=>{const b=document.createElement("button");b.className=`option${state.answers[state.current]===i?" selected":""}`;b.type="button";b.innerHTML=`<span class="key">${L[i]}</span><span>${esc(o)}</span>`;b.onclick=()=>{state.answers[state.current]=i;renderQuestion();renderProgress()};list.append(b)});$("#prevQuestion").disabled=state.current===0;$("#nextQuestion").disabled=state.current===state.questions.length-1;$("#flagQuestion").textContent=state.flags[state.current]?"Hapus Ragu":"Tandai Ragu";renderNumberState()}
function renderNumberState(){[...$("#numberGrid").children].forEach((b,i)=>{b.className="num";if(i===state.current)b.classList.add("active");if(state.answers[i]!==null)b.classList.add("answered");if(state.flags[i])b.classList.add("flagged")})}
function renderProgress(){const a=state.answers.filter(x=>x!==null).length;$("#answeredCount").textContent=`${a}/${state.questions.length}`;$("#flaggedCount").textContent=state.flags.filter(Boolean).length;$("#blankCount").textContent=state.questions.length-a;renderNumberState()}
function moveQuestion(d){state.current=Math.min(Math.max(state.current+d,0),state.questions.length-1);renderQuestion()}
function toggleFlag(){state.flags[state.current]=!state.flags[state.current];renderQuestion();renderProgress()}
function clearAnswer(){state.answers[state.current]=null;renderQuestion();renderProgress()}
function maxScore(qs){return qs.reduce((a,q)=>a+RULES[q.category].correct,0)}
function calculateResult(){const details=state.questions.map((q,i)=>{const selected=state.answers[i],status=selected===null?"blank":selected===q.answerIndex?"correct":"wrong",score=status==="blank"?0:status==="correct"?RULES[q.category].correct:RULES[q.category].wrong;return{index:i,question:q,selected,status,score}}),categoryStats=Object.fromEntries(Object.keys(RULES).map(c=>[c,{total:0,correct:0,wrong:0,blank:0,score:0,max:0}]));details.forEach(d=>{const s=categoryStats[d.question.category];s.total++;s[d.status]++;s.score+=d.score;s.max+=RULES[d.question.category].correct});return{participant:state.participant,startedAt:state.startedAt.toISOString(),finishedAt:new Date().toISOString(),totalScore:details.reduce((a,d)=>a+d.score,0),maxScore:maxScore(state.questions),answered:state.answers.filter(a=>a!==null).length,blank:state.answers.filter(a=>a===null).length,flagged:state.flags.filter(Boolean).length,categoryStats,details}}
function finishExam(){clearInterval(state.timerId);state.result=calculateResult();$("#examPanel").classList.add("hidden");$("#resultPanel").classList.remove("hidden");$("#scoreTotal").textContent=state.result.totalScore.toFixed(6);$("#resultSummary").textContent=`${state.result.participant} menjawab ${state.result.answered} dari ${state.questions.length} soal. Nilai maksimal paket ini ${state.result.maxScore.toFixed(6)}.`;renderReport();renderReview()}
function renderReport(){const el=$("#categoryReport");el.innerHTML="";Object.entries(RULES).forEach(([c,r])=>{const s=state.result.categoryStats[c],card=document.createElement("article");card.className="card report-card";card.innerHTML=`<h2>${r.label}</h2><div class="metric"><div><span>Jumlah</span><strong>${s.total}</strong></div><div><span>Skor</span><strong>${s.score.toFixed(6)}</strong></div><div><span>Benar</span><strong>${s.correct}</strong></div><div><span>Salah</span><strong>${s.wrong}</strong></div><div><span>Kosong</span><strong>${s.blank}</strong></div><div><span>Maksimal</span><strong>${s.max.toFixed(6)}</strong></div></div>`;el.append(card)})}
function renderReview(){const el=$("#reviewPanel");el.innerHTML="";state.result.details.forEach(d=>{const q=d.question,sel=d.selected===null?"Tidak dijawab":`${L[d.selected]}. ${q.options[d.selected]}`,cor=`${L[q.answerIndex]}. ${q.options[q.answerIndex]}`,it=document.createElement("article");it.className=`review-item ${d.status==="correct"?"correct":d.status==="wrong"?"wrong":""}`;it.innerHTML=`<h3>${d.index+1}. ${esc(q.question)}</h3><p><strong>Modul:</strong> ${esc(q.module)} | <strong>Kategori:</strong> ${RULES[q.category].label} | <strong>Skor:</strong> ${d.score.toFixed(6)}</p><p><strong>Jawaban Anda:</strong> ${esc(sel)}</p><p><strong>Kunci:</strong> ${esc(cor)}</p><p><strong>Pembahasan:</strong> ${esc(q.explanation)}</p>`;el.append(it)})}
function resetExam(){clearInterval(state.timerId);$("#startPanel").classList.remove("hidden");$("#examPanel").classList.add("hidden");$("#resultPanel").classList.add("hidden");$("#reviewPanel").classList.add("hidden")}
function exportResult(){if(!state.result)return;const blob=new Blob([JSON.stringify(state.result,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`hasil-tryout-ppat-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
function moduleNames(){return[...new Set(BANK.map(q=>q.module))].sort((a,b)=>a.localeCompare(b))}
function initLms(){const m=moduleNames();$("#moduleSelect").innerHTML=m.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join("");renderModuleStats();loadLmsModule(m[0])}
function renderModuleStats(){const el=$("#moduleStats");el.innerHTML="";moduleNames().forEach(n=>{const item=document.createElement("div");item.className="module-stat";item.innerHTML=`<strong>${esc(n)}</strong><span>${BANK.filter(q=>q.module===n).length} soal belajar</span>`;el.append(item)})}
function loadLmsModule(n){lms.questions=sh(BANK.filter(q=>q.module===n)).map(wopt);lms.current=0;lms.locked=false;renderLms()}
function renderLms(){const q=lms.questions[lms.current];if(!q)return;$("#lmsProgress").textContent=`${lms.current+1}/${lms.questions.length}`;$("#lmsCategory").textContent=RULES[q.category].label;$("#lmsModule").textContent=q.module;$("#lmsQuestion").textContent=q.question;$("#lmsFeedback").classList.add("hidden");const el=$("#lmsOptions");el.innerHTML="";q.options.forEach((o,i)=>{const b=document.createElement("button");b.className="option";b.type="button";b.innerHTML=`<span class="key">${L[i]}</span><span>${esc(o)}</span>`;b.onclick=()=>answerLms(i);el.append(b)});$("#lmsPrev").disabled=lms.current===0;$("#lmsNext").disabled=lms.current===lms.questions.length-1}
function answerLms(i){if(lms.locked)return;lms.locked=true;const q=lms.questions[lms.current],ok=i===q.answerIndex;[...$("#lmsOptions").children].forEach((b,j)=>{b.disabled=true;if(j===q.answerIndex)b.classList.add("correct");if(j===i&&!ok)b.classList.add("wrong")});const f=$("#lmsFeedback");f.className=`feedback ${ok?"correct":"wrong"}`;f.innerHTML=`<strong>${ok?"Benar.":"Belum tepat."}</strong><p><strong>Kunci:</strong> ${L[q.answerIndex]}. ${esc(q.options[q.answerIndex])}</p><p>${esc(q.explanation)}</p>`;f.classList.remove("hidden")}
function moveLms(d){lms.current=Math.min(Math.max(lms.current+d,0),lms.questions.length-1);lms.locked=false;renderLms()}
function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
$("#tabTryout").onclick=()=>setTab("tryout");$("#tabLms").onclick=()=>setTab("lms");$("#startExam").onclick=startExam;$("#reshufflePreview").onclick=()=>alert(`Paket acak siap: ${buildPacket().length} soal dengan prioritas soal berbobot.`);$("#prevQuestion").onclick=()=>moveQuestion(-1);$("#nextQuestion").onclick=()=>moveQuestion(1);$("#flagQuestion").onclick=toggleFlag;$("#clearAnswer").onclick=clearAnswer;$("#submitExam").onclick=()=>{const b=state.answers.filter(a=>a===null).length;if(confirm(b?`Masih ada ${b} soal kosong. Submit sekarang?`:"Submit tryout sekarang?"))finishExam()};$("#reviewToggle").onclick=()=>{$("#reviewPanel").classList.toggle("hidden");$("#reviewToggle").textContent=$("#reviewPanel").classList.contains("hidden")?"Review Pembahasan":"Sembunyikan Review"};$("#newExam").onclick=resetExam;$("#exportResult").onclick=exportResult;$("#moduleSelect").onchange=e=>loadLmsModule(e.target.value);$("#lmsPrev").onclick=()=>moveLms(-1);$("#lmsNext").onclick=()=>moveLms(1);renderBankStats();initLms();
